### ISSUE TITLE
Nevyplněné labely, vycentrování formuláře na střed

### ISSUE THREAD

**Issue by MichalNemec** [nextras/forms#23]
Pokud si nevplním label, tak se zobrazí nevyplněný label (col-md-3) a prvky (col-md-9) se zobrazí na druhé polovině obrazovky. 

Je nějaká možnost vypnout ten label, aby byl na centru obrazovky, aniž bych editoval toto?

```
$this->wrappers['control']['container'] = 'div class=col-sm-12';        /* col-md-9 */
$this->wrappers['label']['container'] = 'div class="control-label"';     /* col-md-3 */
```

**Comment by hrach** [comment]
Closing, current behavior is wanted.
