### ISSUE TITLE
Fix method parameters declaration in BS3InputMacros

### ISSUE THREAD

**Issue by rebendajirijr** [nextras/forms#30]
Following lines [BS3InputMacros#L21](https://github.com/nextras/forms/blob/master/src/Bridges/Latte/Macros/BS3InputMacros.php#L21), [BS3InputMacros#L31](https://github.com/nextras/forms/blob/master/src/Bridges/Latte/Macros/BS3InputMacros.php#L31) are not compatible with parent declaration.

**Comment by hrach** [comment]
ouch :|

**Comment by hrach** [comment]
srr for this, I pushed old code.
