### ISSUE TITLE
Bootstrap error rendering

### ISSUE THREAD

**Issue by medhi** [nextras/forms#33]
Please, modify form errors rendering to Bootstrap's `.alert-danger` divs. Now form errors are unstyled.

Thanks!

**Comment by hrach** [comment]
Shouldn't it be done by has-error & help-block classes?

**Comment by medhi** [comment]
Yes, for errors in particular fields, but not for global error messages. Both should be fine to implement, so one could render the form just with `{control myForm}`.

**Comment by TomasVotruba** [comment]
What's the status of this?

@medhi Could you send PR?

**Comment by pavelkouril** [comment]
Since @medhi didn't send it, I created it #37 - could you have a look?
