### ISSUE TITLE
Snippet support

### ISSUE THREAD

**Issue by wodCZ** [nextras/forms#35]
I have implemented `ComponentControl` and tried to use snippets, but there are two problems.

One is that invalidateControl method (in TemplateControlTrait) should be deprecated and replaced with redrawControl (outdated implementation). Probably ComponentControl would implement `\Nette\Application\UI\IRenderable`.

Second problem is IMHO larger, because of [typehint in UIRuntime](https://github.com/nette/application/blob/master/src/Bridges/ApplicationLatte/UIRuntime.php#L21), which needs UI\Control.
I'm not sure if you have gone around this (code looks like that) or is it new in Nette.

Here are few thoughts to "fix" this:
 - PullRequest to Nette with usage of interfaces instead of abstract class in UIRuntime
 - Some reflection hacks
 - Own snippet macro, with implementation from point 1

**Comment by hrach** [comment]
Well, I have a feeling that such typehint was alredy removed, but it seems it's back. :| will investigate and try to find that issue.
