### ISSUE TITLE
Nette 2.4: DatePicker false invalid result of validation

### ISSUE THREAD

**Issue by miloshavlicek** [nextras/forms#48]
Nette 2.4.1
PHP 7.1

Since upgrading to Nette 2.4 I face this issue:

Form factory:
```
use Nette\Application\UI\Form;

$form = new Form;
$form->addDatePicker('born', 'Datum narození:')
            ->setRequired('Vyplňte, prosím, datum narození.')
            ->addRule(Form::RANGE, 'Datum narození je příliš staré.',
                [new DateTime('-150 years'), NULL])
            ->addRule(Form::RANGE, 'Musíte být starší než 15 let.',
                [NULL, new DateTime('-15 years')])
            ->getControlPrototype()
            ->addClass('maxwidth-350 form-control');
```

Render result:
`<input type="text" name="born" class="maxwidth-350 form-control date" id="frm-Career_ApplicantFormSection-careerForm-born" required="" data-nette-rules="[{&quot;op&quot;:&quot;:filled&quot;,&quot;msg&quot;:&quot;Vyplňte, prosím, datum narození.&quot;},{&quot;op&quot;:&quot;:range&quot;,&quot;msg&quot;:&quot;Datum narození je příliš staré.&quot;,&quot;arg&quot;:[&quot;1867-05-16T09:33:15+01:00&quot;,null]},{&quot;op&quot;:&quot;:range&quot;,&quot;msg&quot;:&quot;Musíte být starší než 15 let.&quot;,&quot;arg&quot;:[null,&quot;2002-05-16T09:33:15+02:00&quot;]}]" min="1867-05-16" max="2002-05-16">`

I use this JS file for Nette forms validation:
https://github.com/nette/forms/blob/master/src/assets/netteForms.js

When I pick in DatePicker valid date e.g.: 16th May 2001, result is error: "Datum narození je příliš staré."

**Comment by miloshavlicek** [comment]
Issue seems to be caused by compatibility with the new Nette Forms JS file. Without it, everything works ok.

**Comment by hrach** [comment]
Isn't this connected with this issue? https://github.com/nette/forms/issues/146#issuecomment-297332345

**Comment by miloshavlicek** [comment]
Yes, exactly... However, I use latest dev version of nette/forms and nette/utils and it's still the same problem. I think the problem is in netteForms.js. I continue in investigation...

**Comment by hrach** [comment]
Would be great if you ping David there, that's still a bug.

**Comment by hrach** [comment]
Upstream issue fixed long time ago :)
