### ISSUE TITLE
Add support for Nette 3

### ISSUE THREAD

**Issue by foxycode** [nextras/forms#60]
Do you plan in in near future?

**Comment by hrach** [comment]
The components part has been separated/reworked (because it's not possible make it the same way in Nette 3.0) and is exlusively Nette 3+ https://github.com/nextras/form-components

The rendering will be reworked hopefully soon.

**Comment by foxycode** [comment]
Thanks for info. Unfortunately, what I need is `BS3FormRenderer` :(

**Comment by hrach** [comment]
PRs are welcomed, I will do something this weekend :)

**Comment by jtojnar** [comment]
Do you know if it is possible to reproduce `ComponentControlTrait` in Nette 3? I am using it to create a control composed of two sub-controls:

https://github.com/jtojnar/entries/blob/348ad2958040f45ec27e9ab561eaf28d02f86bf5/app/components/SportidentControl.php#L18-L19
https://github.com/jtojnar/entries/blob/348ad2958040f45ec27e9ab561eaf28d02f86bf5/app/components/SportidentControl.php#L36-L43

**Comment by hrach** [comment]
it is done in the new repository, though from the other side.

**Comment by jtojnar** [comment]
Thanks, I somehow missed the Fragments directory.

https://github.com/jtojnar/entries/commit/c6e44130e32373a6f0c71623dc1566c2892b6fd8#diff-4078d83a9a0ef325c67991359ddfe536

This seems to have worked – though I am somewhat wary of the created input:

https://github.com/nextras/form-components/blob/44fa26abb183f360fc4aa88aaa327c2e6a5222b2/src/Fragments/Traits/BaseControlTrait.php#L70
